micronaut:
  application:
    name: messageroutingservice
  metrics:
    enabled: true
    export:
      cloudwatch:
        enabled: true
  server:
    port: 8085

redis.uri: redis://localhost

sqs.message-queue-name: message_queue
